apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "chaos.fullname" . }}-noms
  labels:
    app: {{ template "chaos.name" . }}
    chart: {{ template "chaos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "chaos.name" . }}-noms
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chaos.name" . }}-noms
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: noms
        image: "{{ .Values.noms.image.repository }}:{{ .Values.noms.image.tag }}"
        imagePullPolicy: {{ .Values.noms.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.noms.port }}
        volumeMounts:
        - mountPath: "/data"
          name: noms-volume
      volumes:
      - name: noms-volume
        persistentVolumeClaim:
          claimName: {{ template "chaos.fullname" . }}-noms-claim
