{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-tendermint
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-tendermint
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-tendermint
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.minikube }}
      imagePullSecrets:
      - name: awsecr-cred
      {{ end }}
      initContainers:
      # Uses chaosnode image to get empty hash and saves it
      - name: waits
        image: "{{ .Values.chaos.deployUtils.image.repository }}:{{ .Values.chaos.deployUtils.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.deployUtils.image.pullPolicy }}
        command: ["/bin/bash", "/root/startup-waits.sh"]
        volumeMounts:
        - mountPath: /root/startup-waits.sh
          name: chaos-tendermint-config
          subPath: startup-waits.sh
        - mountPath: /root/lib
          name: script-lib
      - name: hash
        image: "{{ .Values.chaosnode.image.repository }}:{{ .Values.chaosnode.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.tendermint.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - /bin/chaosnode -echo-hash -spec http://{{ template "nodegroup.fullname" . }}-chaos-noms-service:{{ .Values.chaos.noms.port }} >&1 | tail -n 1 | tr -d '[:space:]' > /tendermint/app_hash
        env:
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}
        volumeMounts:
        - name: tendermint-home-volume
          mountPath: /tendermint
        - mountPath: /root/lib
          name: script-lib
      containers:
      - name: tendermint
        image: "{{ .Values.chaos.tendermint.image.repository }}:{{ .Values.chaos.tendermint.image.tag }}"
        command: ["/bin/bash", "/root/tendermint-start.sh"]
        imagePullPolicy: {{ .Values.chaos.tendermint.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.chaos.tendermint.ports.p2p }}
          - containerPort: {{ .Values.chaos.tendermint.ports.rpc }}
        volumeMounts:
        - mountPath: /tendermint
          name: tendermint-home-volume
        - mountPath: /root/lib
          name: script-lib

        # scripts
        - mountPath: /root/liveness-decoy.sh
          name: nodegroup-config
          subPath: liveness-decoy.sh
        - mountPath: /root/shutdown-waits.sh
          name: chaos-tendermint-config
          subPath: shutdown-waits.sh
        - mountPath: /root/startup-waits.sh
          name: chaos-tendermint-config
          subPath: startup-waits.sh
        - mountPath: /root/make-snapshot.sh
          name: chaos-tendermint-config
          subPath: make-snapshot.sh
        - mountPath: /root/tendermint-init.sh
          name: nodegroup-config
          subPath: tendermint-init.sh
        - mountPath: /root/tendermint-start.sh
          name: nodegroup-config
          subPath: tendermint-start.sh
        - mountPath: /root/restore-snapshot.sh
          name: nodegroup-config
          subPath: restore-snapshot.sh
        - mountPath: /root/redis-cli.sh
          name: nodegroup-config
          subPath: redis-cli.sh

        # read only config files
        - mountPath: /root/config-ro/genesis.json
          name: chaos-tendermint-config
          subPath: genesis.json
        - mountPath: /root/config-ro/node_key.json
          name: chaos-tendermint-config
          subPath: node_key.json
        - mountPath: /root/config-ro/priv_validator_key.json
          name: chaos-tendermint-config
          subPath: priv_validator_key.json
        - mountPath: /root/data-ro/priv_validator_state.json
          name: chaos-tendermint-config
          subPath: priv_validator_state.json
        - mountPath: /root/config-ro/config.toml
          name: chaos-tendermint-config
          subPath: config.toml
        readinessProbe:
          tcpSocket:
            port: {{ .Values.chaos.tendermint.ports.p2p }}
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.chaos.tendermint.ports.p2p }}
          initialDelaySeconds: 30
          periodSeconds: 10

        env:
        - name: SNAPSHOTGUN_ENABLED
          value: "{{ .Values.snapshot.enabled }}"
        - name: AWS_KEY
          value: {{ .Values.aws.accessKeyID }}
        - name: AWS_SECRET
          value: {{ .Values.aws.secretAccessKey }}
        - name: R_HOST # for snapshot coordination
          value: {{ template "nodegroup.fullname" . }}-snapshot-redis
        - name: TMHOME
          value: "/tendermint"
        - name: THIS_SERVICE
          value: chaos-tm
        - name: CHAIN # for downloading snapshots
          value: "chaos"
        - name: P2P_PORT
          value: {{ .Values.chaos.tendermint.ports.p2p | quote }}
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}
        - name: NODE_ID
          value: {{ .Values.chaos.tendermint.moniker }}
        - name: PERSISTENT_PEERS
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
              key: persistentPeers
        - name: SNAPSHOT_CODE
          value: {{ .Values.chaos.noms.snapshotCode }}
      volumes:
        - name: tendermint-home-volume
          persistentVolumeClaim:
            claimName: {{ template "nodegroup.fullname" . }}-chaos-tendermint-claim
        - name: script-lib
          configMap:
            name: {{ template "nodegroup.fullname" . }}-scripts
        - name: chaos-tendermint-config
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
        - name: nodegroup-config
          configMap:
            name: {{ template "nodegroup.fullname" . }}-nodegroup-config
      resources:
        requests:
          memory: {{ .Values.chaos.tendermint.resources.requests.memory }}
          cpu: {{ .Values.chaos.tendermint.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.tendermint.resources.limits.memory }}
          cpu: {{ .Values.chaos.tendermint.resources.limits.cpu }}

{{ end }}
