{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodeGroup.fullname" . }}-chaos-noms
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodeGroup.name" . }}-chaos-noms
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodeGroup.name" . }}-chaos-noms
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: noms
        image: "{{ .Values.chaos.noms.image.repository }}:{{ .Values.chaos.noms.image.tag }}"
        command: ["/bin/sh"]
        args: ["-c", "cd /data && base64 -d data.tar.gz | gunzip -c | tar xvf - && noms serve /data"]
        imagePullPolicy: {{ .Values.chaos.noms.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.chaos.noms.port }}
        volumeMounts:
        - name: noms-volume
          mountPath: /data
        - name: noms-data
          mountPath: /data/data.tar.gz
          subPath: data.tar.gz      
      volumes:
      - name: noms-volume
        persistentVolumeClaim:
          claimName: {{ template "nodeGroup.fullname" . }}-chaos-noms-claim
      - name: noms-data
        configMap:
          name: {{ template "nodeGroup.fullname" . }}-chaos-noms-config
          items:
          - key: noms-start.sh
            path: noms-start.sh
      - name: snapshot-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
          items:
          - key: snapshot.sh
            path: snapshot.sh
      resources:
        requests:
          memory: {{ .Values.chaos.noms.resources.requests.memory }}
          cpu: {{ .Values.chaos.noms.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.noms.resources.limits.memory }}
          cpu: {{ .Values.chaos.noms.resources.limits.cpu }}


{{ end }}
