{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-tendermint
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-tendermint
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-tendermint
        release: {{ .Release.Name }}
    spec:
      initContainers:
      # Uses chaosnode image to get empty hash and saves it
      - name: noms-wait
        image: "{{ .Values.ndau.deployUtils.image.repository }}:{{ .Values.ndau.deployUtils.image.tag }}"
        imagePullPolicy: {{ .Values.ndau.deployUtils.image.pullPolicy }}
        command: ["sh", "-c", "echo starting noms wait loop; until curl -v {{ template "nodegroup.fullname" . }}-chaos-noms-service:{{ .Values.chaos.noms.port }} --connect-timeout 5; do echo waiting for {{ template "nodegroup.fullname" . }}-chaos-noms-service; sleep 5; done;"]
      - name: hash
        image: "{{ .Values.chaosnode.image.repository }}:{{ .Values.chaosnode.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.tendermint.image.pullPolicy }}
        command: ["/bin/sh"]
        args: [
          "-c",
          "/bin/chaosnode -echo-hash -spec http://{{ template "nodegroup.fullname" . }}-chaos-noms-service:{{ .Values.chaos.noms.port }} >&1 | tail -n 1 | tr -d '[:space:]' > /tendermint/app_hash",
        ]
        env:
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}
        volumeMounts:
        - name: tendermint-home-volume
          mountPath: /tendermint
      containers:
      - name: tendermint
        image: "{{ .Values.chaos.tendermint.image.repository }}:{{ .Values.chaos.tendermint.image.tag }}"
        command: ["/bin/sh"]
        args: ["/root/tendermint-start.sh"]
        imagePullPolicy: {{ .Values.chaos.tendermint.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.chaos.tendermint.ports.p2p }}
          - containerPort: {{ .Values.chaos.tendermint.ports.rpc }}
        volumeMounts:
        - mountPath: /tendermint
          name: tendermint-home-volume

        # scripts
        - name: tendermint-init-sh
          mountPath: /root/tendermint-init.sh
          subPath: tendermint-init.sh
        - name: tendermint-start-sh
          mountPath: /root/tendermint-start.sh
          subPath: tendermint-start.sh
        - name: snapshot-sh
          mountPath: /root/snapshot.sh
          subPath: snapshot.sh

        # read only config files
        - name: genesis-json
          mountPath: /root/config-ro/genesis.json
          subPath: genesis.json
        - name: node-key-json
          mountPath: /root/config-ro/node_key.json
          subPath: node_key.json
        - name: priv-validator-json
          mountPath: /root/config-ro/priv_validator_key.json
          subPath: priv_validator_key.json
        - name: config-toml
          mountPath: /root/config-ro/config.toml
          subPath: config.toml
        env:
        - name: TMHOME
          value: "/tendermint"
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}
        - name: UPDATE_PERSISTENT_PEERS
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-peers
              key: updatePeerAddresses
        - name: PERSISTENT_PEERS
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-peers
              key: addresses
        - name: PRIVATE_PEER_IDS
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-peers
              key: privatePeerIds
        - name: SNAPSHOT_CODE
          value: {{ .Values.chaos.noms.snapshotCode }}
        - name: DOWNLOAD_SNAPSHOT
          value: {{ .Values.chaos.noms.downloadSnapshot }}
        - name: RELEASE_TOKEN
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-nodegroup-config
              key: release-token
      volumes:
        - name: tendermint-home-volume
          persistentVolumeClaim:
            claimName: {{ template "nodegroup.fullname" . }}-chaos-tendermint-claim

        # read only config files
        - name: config-toml
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
            items:
            - key: config.toml
              path: config.toml
        - name: genesis-json
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
            items:
            - key: genesis.json
              path: genesis.json
        - name: priv-validator-json
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
            items:
            - key: priv_validator_key.json
              path: priv_validator_key.json
        - name: node-key-json
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
            items:
            - key: node_key.json
              path: node_key.json

        # Scripts
        - name: snapshot-sh
          configMap:
            name: {{ template "nodegroup.fullname" . }}-nodegroup-config
            items:
            - key: snapshot.sh
              path: snapshot.sh
        - name: tendermint-init-sh
          configMap:
            name: {{ template "nodegroup.fullname" . }}-nodegroup-config
            items:
            - key: tendermint-init.sh
              path: tendermint-init.sh
        - name: tendermint-start-sh
          configMap:
            name: {{ template "nodegroup.fullname" . }}-chaos-tendermint-config
            items:
            - key: tendermint-start.sh
              path: tendermint-start.sh
      resources:
        requests:
          memory: {{ .Values.chaos.tendermint.resources.requests.memory }}
          cpu: {{ .Values.chaos.tendermint.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.tendermint.resources.limits.memory }}
          cpu: {{ .Values.chaos.tendermint.resources.limits.cpu }}

{{ end }}
