{{ if .Values.chaos.enabled }}

# This is blank, it gets filled in with the argument tendermint is expecting.
# A list of address@ip:port, separated by commas.
kind: ConfigMap
metadata:
  name: {{ template "nodeGroup.fullname" . }}-chaos-tendermint-peers
apiVersion: v1
data:
  addresses: {{ default "" ( b64dec .Values.chaos.tendermint.persistentPeers ) | quote }}
  updatePeerAddresses: {{ default "false" .Values.chaos.tendermint.updatePeerAddresses | quote }}
  privatePeerIds: {{ default "" .Values.chaos.tendermint.privatePeerIds | quote }}

{{ end }}
