{{ if .Values.chaos.enabled }}

kind: ConfigMap
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaosnode-config
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
apiVersion: v1
data:
  chaosnode-start.sh: |
    chaosnode --set-ndaunode $(cat /root/.ndau/ndau-address)

    /bin/bash /root/startup-waits.sh
    chaosnode \
      -spec http://{{ template "nodegroup.fullname" . }}-chaos-noms-service:{{ .Values.chaos.noms.port }} \
      -addr 0.0.0.0:{{ required ".Values.chaosnode.port required" .Values.chaosnode.port }} \
      -index {{ template "nodegroup.fullname" . }}-chaos-redis-service:{{ .Values.chaos.redis.port }}

  startup-waits.sh: |
    errcho() {
      >&2 echo $@
    }

    wait_for() {
      service=$1
      pod=$2
      port=$3

      errcho starting $service wait loop
      until nc -z -w 1 $pod $port; do
        errcho waiting for $pod on $port to accept connection
        sleep 2
      done
    }

    errcho "Starting wait loops"
    wait_for redis {{ template "nodegroup.fullname" . }}-chaos-redis-service {{ .Values.chaos.redis.port }}
    wait_for noms {{ template "nodegroup.fullname" . }}-chaos-noms-service {{ .Values.chaos.noms.port }}

  shutdown-waits.sh: |
    errcho() {
      >&2 echo $@
    }

    wait_for() {
      service=$1
      pod=$2
      port=$3

      errcho starting $service wait loop
      until ! nc -z -w 1 $pod $port; do
        errcho waiting for $pod on $port to accept connection
        sleep 2
      done
    }

    errcho "Starting shutdown wait loops"

  shutdown-waits.sh: |
    errcho() {
      >&2 echo $@
    }

    wait_for() {
      service=$1
      pod=$2
      port=$3

      errcho starting $service wait loop
      until ! nc -z -w 1 $pod $port; do
        errcho waiting for $pod on $port to accept connection
        sleep 2
      done
    }

    errcho "Starting shutdown wait loops"
    wait_for redis {{ template "nodegroup.fullname" . }}-ndaunode-service {{ .Values.ndaunode.port }}
    errcho "Done"    errcho "Done"

{{ end }}
