{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-redis
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-redis
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      {{ if .Values.minikube }}
      imagePullSecrets:
      - name: awsecr-cred
      {{ end }}
      containers:
      - name: redis
        image: "{{ .Values.chaos.redis.image.repository }}:{{ .Values.chaos.redis.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.redis.image.pullPolicy }}
        command:
          - /bin/bash
          - /root/redis-start.sh
        readinessProbe:
          tcpSocket:
            port: {{ .Values.chaos.redis.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.chaos.redis.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: SNAPSHOTGUN_ENABLED
          value: "{{ .Values.snapshot.enabled }}"
        - name: AWS_KEY
          value: {{ .Values.aws.accessKeyID }}
        - name: AWS_SECRET
          value: {{ .Values.aws.secretAccessKey }}
        - name: REDIS_PORT
          value: "{{ .Values.chaos.redis.port }}"
        - name: R_HOST # for snapshot coordination
          value: {{ template "nodegroup.fullname" . }}-snapshot-redis
        - name: THIS_SERVICE
          value: chaos-redis
        - name: CHAIN
          value: chaos
        - name: NDAUHOME
          value: /redis
        ports:
        - containerPort: {{ .Values.chaos.redis.port }}
        volumeMounts:
        - name: redis-volume
          mountPath: /redis
        - mountPath: /root/shutdown-waits.sh
          name: chaos-redis-config
          subPath: shutdown-waits.sh
        - mountPath: /root/make-snapshot.sh
          name: chaos-redis-config
          subPath: make-snapshot.sh
        - mountPath: /root/redis-start.sh
          name: nodegroup-config
          subPath: redis-start.sh
        - mountPath: /root/redis-cli.sh
          name: nodegroup-config
          subPath: redis-cli.sh
        - mountPath: /root/restore-snapshot.sh
          name: nodegroup-config
          subPath: restore-snapshot.sh
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: {{ template "nodegroup.fullname" . }}-chaos-redis-claim
      - name: nodegroup-config
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
      - name: chaos-redis-config
        configMap:
          name: {{ template "nodegroup.fullname" . }}-chaos-redis
      resources:
        requests:
          memory: {{ .Values.chaos.redis.resources.requests.memory }}
          cpu: {{ .Values.chaos.redis.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.redis.resources.limits.memory }}
          cpu: {{ .Values.chaos.redis.resources.limits.cpu }}

{{ end }}
