{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-noms
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-noms
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-noms
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.minikube }}
      imagePullSecrets:
      - name: awsecr-cred
      {{ end }}
      containers:
      - name: noms
        image: "{{ .Values.chaos.noms.image.repository }}:{{ .Values.chaos.noms.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.noms.image.pullPolicy }}
        command:
          - /bin/bash
          - /root/noms-start.sh
        readinessProbe:
          tcpSocket:
            port: {{ .Values.chaos.noms.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ .Values.chaos.noms.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: SNAPSHOTGUN_ENABLED
          value: "{{ .Values.snapshot.enabled }}"
        - name: AWS_KEY
          value: {{ .Values.aws.accessKeyID }}
        - name: AWS_SECRET
          value: {{ .Values.aws.secretAccessKey }}
        - name: R_HOST # for snapshot coordination
          value: {{ template "nodegroup.fullname" . }}-snapshot-redis
        - name: CHAIN
          value: "chaos"
        - name: THIS_SERVICE
          value: chaos-noms
        - name: SNAPSHOT_CODE
          value: {{ .Values.chaos.noms.snapshotCode }}
        ports:
        - containerPort: {{ .Values.chaos.noms.port }}
        volumeMounts:
        - name: noms-start-sh
          mountPath: /root/noms-start.sh
          subPath: noms-start.sh
        - name: make-snapshot-sh
          mountPath: /root/make-snapshot.sh
          subPath: make-snapshot.sh
        - name: snapshot-sh
          mountPath: /root/restore-snapshot.sh
          subPath: restore-snapshot.sh
        - name: redis-cli-sh
          mountPath: /root/redis-cli.sh
          subPath: redis-cli.sh
        - name: noms-volume
          mountPath: /noms
      volumes:
      - name: noms-start-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
          items:
          - key: noms-start.sh
            path: noms-start.sh
      - name: noms-volume
        persistentVolumeClaim:
          claimName: {{ template "nodegroup.fullname" . }}-chaos-noms-claim
      # scripts
      - name: snapshot-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
          items:
          - key: restore-snapshot.sh
            path: restore-snapshot.sh
      - name: redis-cli-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
          items:
          - key: redis-cli.sh
            path: redis-cli.sh
      - name: make-snapshot-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-chaos-noms-config
          items:
          - key: make-snapshot.sh
            path: make-snapshot.sh
      resources:
        requests:
          memory: {{ .Values.chaos.noms.resources.requests.memory }}
          cpu: {{ .Values.chaos.noms.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.noms.resources.limits.memory }}
          cpu: {{ .Values.chaos.noms.resources.limits.cpu }}


{{ end }}
