{{ if .Values.chaos.enabled }}

kind: ConfigMap
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-noms-config
apiVersion: v1
data:
  noms-start.sh: |
    #!/bin/sh

    mkdir -p /noms/data

    DATA_DIR=/noms/data \
    DATA_EXISTS_FILE=/noms/data/manifest \
    FLAG_DIR=/noms \
    SNAPSHOT_FILE=chaos-noms.tgz \
    LOG_TAG=chaos-noms \
      /bin/sh /root/snapshot.sh

    noms serve /noms/data

{{ end }}
