{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-noms
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-noms
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-noms
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.minikube }}
      imagePullSecrets:
      - name: awsecr-cred
      {{ end }}
      containers:
      - name: noms
        image: "{{ .Values.chaos.noms.image.repository }}:{{ .Values.chaos.noms.image.tag }}"
        imagePullPolicy: {{ .Values.chaos.noms.image.pullPolicy }}
        command: ["/bin/sh"]
        args: ["/root/noms-start.sh"]
        env:
        - name: SNAPSHOT_CODE
          value: {{ .Values.ndau.noms.snapshotCode }}
        - name: DOWNLOAD_SNAPSHOT
          value: {{ .Values.ndau.noms.downloadSnapshot }}
        - name: RELEASE_TOKEN
          valueFrom:
            configMapKeyRef:
              name: {{ template "nodegroup.fullname" . }}-nodegroup-config
              key: release-token
        ports:
        - containerPort: {{ .Values.chaos.noms.port }}
        volumeMounts:
        - name: noms-start-sh
          mountPath: /root/noms-start.sh
          subPath: noms-start.sh
        - name: snapshot-sh
          mountPath: /root/snapshot.sh
          subPath: snapshot.sh
        - name: noms-volume
          mountPath: /noms
      volumes:
      - name: noms-volume
        persistentVolumeClaim:
          claimName: {{ template "nodegroup.fullname" . }}-chaos-noms-claim
      # scripts
      - name: noms-start-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-chaos-noms-config
          items:
          - key: noms-start.sh
            path: noms-start.sh
      - name: snapshot-sh
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
          items:
          - key: snapshot.sh
            path: snapshot.sh
      resources:
        requests:
          memory: {{ .Values.chaos.noms.resources.requests.memory }}
          cpu: {{ .Values.chaos.noms.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.noms.resources.limits.memory }}
          cpu: {{ .Values.chaos.noms.resources.limits.cpu }}


{{ end }}
