{{ if .Values.chaos.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-chaos-redis
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-chaos-redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-chaos-redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.chaos.redis.image.repository }}:{{ .Values.chaos.redis.image.tag }}"
        command: ["redis-server"]
        args: ["--dir", "/redis", "--save", "60", "1", "--tcp-backlog", "128", "--port", "{{ .Values.ndau.redis.port }}"]
        imagePullPolicy: {{ .Values.chaos.redis.image.pullPolicy }}
        env:
        - name: NDAUHOME
          value: /redis
        ports:
        - containerPort: {{ .Values.chaos.redis.port }}
        volumeMounts:
        - name: redis-volume
          mountPath: /redis
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: {{ template "nodegroup.fullname" . }}-chaos-redis-claim
      resources:
        requests:
          memory: {{ .Values.chaos.redis.resources.requests.memory }}
          cpu: {{ .Values.chaos.redis.resources.requests.cpu }}
        limits:
          memory: {{ .Values.chaos.redis.resources.limits.memory }}
          cpu: {{ .Values.chaos.redis.resources.limits.cpu }}

{{ end }}
