{{ if .Values.ndau.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ template "nodegroup.fullname" . }}-ndau-redis-service
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ndau.redis.service.type }}
  ports:
    - port: {{ .Values.ndau.redis.port }}
      targetPort: {{ .Values.ndau.redis.port }}
      protocol: TCP
  selector:
    app: {{ template "nodegroup.name" . }}-ndau-redis
    release: {{ .Release.Name }}

{{ end }}
