{{ if .Values.ndau.enabled }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndau-noms-claim
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ndau.noms.persistence.size }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndau-redis-claim
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ndau.noms.persistence.size }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndau-tendermint-claim
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ndau.tendermint.persistence.size }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndaunode-claim
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ndau.tendermint.persistence.size }}

{{ end }}
