apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-ndauapi
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ndauapi.replicas }}
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-ndauapi
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-ndauapi
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ndauapi
        image: "{{ .Values.ndauapi.image.repository }}:{{ .Values.ndauapi.image.tag }}"
        imagePullPolicy: {{ .Values.ndauapi.image.pullPolicy }}
        env:
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}
        - name: NDAUAPI_NDAU_RPC_URL
          value: http://{{ template "nodegroup.fullname" . }}-ndau-tendermint-service:{{ .Values.ndau.tendermint.ports.rpc }}
        - name: NDAUAPI_CHAOS_RPC_URL
          value: http://{{ template "nodegroup.fullname" . }}-chaos-tendermint-service:{{ .Values.chaos.tendermint.ports.rpc }}
        - name: HONEYCOMB_KEY
          value: {{ .Values.honeycomb.key }}
        - name: HONEYCOMB_DATASET
          value: {{ .Values.honeycomb.dataset }}-ndauapi
        ports:
        - containerPort: {{ .Values.ndauapi.port }}
      resources:
        requests:
          memory: {{ .Values.ndauapi.resources.requests.memory }}
          cpu: {{ .Values.ndauapi.resources.requests.cpu }}
        limits:
          memory: {{ .Values.ndauapi.resources.limits.memory }}
          cpu: {{ .Values.ndauapi.resources.limits.cpu }}
