{{- if .Values.ndauapi.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "nodegroup.fullname" . }}-ndauapi-ingress
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

  annotations:
    kubernetes.io/ingress.class: traefik
{{- with .Values.ndauapi.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.ndauapi.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "nodegroup.fullname" . }}-ndauapi-service
          servicePort: 80
{{- end }}
