{{ if .Values.ndau.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nodegroup.fullname" . }}-ndau-noms
  labels:
    app: {{ template "nodegroup.name" . }}
    chart: {{ template "nodegroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nodegroup.name" . }}-ndau-noms
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nodegroup.name" . }}-ndau-noms
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.minikube }}
      imagePullSecrets:
      - name: awsecr-cred
      {{ end }}
      containers:
      - name: noms
        image: "{{ .Values.ndau.noms.image.repository }}:{{ .Values.ndau.noms.image.tag }}"
        imagePullPolicy: {{ .Values.ndau.noms.image.pullPolicy }}
        command:
          - /bin/bash
          - /root/noms-start.sh
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ndau.noms.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ndau.noms.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: SNAPSHOTGUN_ENABLED
          value: "{{ .Values.snapshot.enabled }}"
        - name: AWS_KEY
          value: {{ .Values.aws.accessKeyID }}
        - name: AWS_SECRET
          value: {{ .Values.aws.secretAccessKey }}
        - name: R_HOST # for snapshot coordination
          value: {{ template "nodegroup.fullname" . }}-snapshot-redis
        - name: THIS_SERVICE
          value: ndau-noms
        - name: CHAIN
          value: "ndau"
        - name: SNAPSHOT_CODE
          value: {{ .Values.ndau.noms.snapshotCode }}
        ports:
        - containerPort: {{ .Values.ndau.noms.port }}
        volumeMounts:
        - name: noms-volume
          mountPath: /noms
        - mountPath: /root/shutdown-waits.sh
          name: ndau-noms-config
          subPath: shutdown-waits.sh
        - mountPath: /root/noms-start.sh
          name: nodegroup-config
          subPath: noms-start.sh
        - mountPath: /root/make-snapshot.sh
          name: ndau-noms-config
          subPath: make-snapshot.sh
        - mountPath: /root/restore-snapshot.sh
          name: nodegroup-config
          subPath: restore-snapshot.sh
        - mountPath: /root/redis-cli.sh
          name: nodegroup-config
          subPath: redis-cli.sh
      volumes:
      - name: noms-volume
        persistentVolumeClaim:
          claimName: {{ template "nodegroup.fullname" . }}-ndau-noms-claim
      - name: ndau-noms-config
        configMap:
          name: {{ template "nodegroup.fullname" . }}-ndau-noms-config
      - name: nodegroup-config
        configMap:
          name: {{ template "nodegroup.fullname" . }}-nodegroup-config
      resources:
        requests:
          memory: {{ .Values.ndau.noms.resources.requests.memory }}
          cpu: {{ .Values.ndau.noms.resources.requests.cpu }}
        limits:
          memory: {{ .Values.ndau.noms.resources.limits.memory }}
          cpu: {{ .Values.ndau.noms.resources.limits.cpu }}

{{ end }}
