{{ if .Values.ndau.enabled }}

kind: ConfigMap
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndau-config
apiVersion: v1
data:
  config.toml: |

    {{ if .Values.ndaunode.chaosLink.enabled }}
    ChaosAddress = {{ .Values.ndaunode.chaosLink.address | quote }}
    UseMock = "" # This needs to be empty if I use the chaos address
    {{ else }}
    ChaosAddress = ""
    UseMock = "/root/.ndau/ndau/mock-chaos.msgp" # This needs to be empty if I use the chaos address
    {{ end }}

    ChaosTimeout = 500 # seconds

    [SystemVariableIndirect]
      Namespace = "qzyAiOhSRWin0sHHU5/Pbecmixk4NVTBNJwFRUeJeJ8="
      Key = "c3Zp"
    [Node]
      Address = "ndaf8jfp9i545r8wf45j7yq7jtbdrdmk2tzad7iqjfmtbue7"
      [Node.Ownership]
        Public = "npuba8jadtbbearqt2i3nir6pn6fftysfvg8c4j6ydpux7c6cx49f6ffy5dxbh5z9zz6sesbmfxs"
        Private = "npvtayjadtcbiaajg4uxy3knuufqu3bsi6dz3ewcnf78gjqcvtz7pr2brt684d8n6hzi6enyeh8gyqcu25ic3vrbpe8mby3k8tqbk7ru8cu5pt4sv759unrzz7zu"
  mock-chaos.msgp: gapOYW1lc3BhY2VzkoKpTmFtZXNwYWNlxAZzeXN0ZW2kRGF0YZKSxAXEA29uZcQRsHN5c3RlbSB2YWx1ZSBvbmWSxAXEA3R3b8QRsHN5c3RlbSB2YWx1ZSB0d2+CqU5hbWVzcGFjZcQgm+f2euwJnj00cy/A+vLkhvYm+Hs6k0z1VY/6qhC9DSKkRGF0YZOSxAXEA29uZcQMq2JwYyB2YWwgb25lksQFxANiYXLEBKNiYXqSxAXEA3N2acT/g6Nmb2+Dp0N1cnJlbnSSxCCb5/Z67AmePTRzL8D68uSG9ib4ezqTTPVVj/qqEL0NIsQDYmFypkZ1dHVyZZLEIJvn9nrsCZ49NHMvwPry5Ib2Jvh7OpNM9VWP+qoQvQ0ixANiYXKoQ2hhbmdlT24Ao29uZYOnQ3VycmVudJLEIJvn9nrsCZ49NHMvwPry5Ib2Jvh7OpNM9VWP+qoQvQ0ixANvbmWmRnV0dXJlksQGc3lzdGVtxANvbmWoQ2hhbmdlT27NA+ijdHdvg6dDdXJyZW50ksQGc3lzdGVtxAN0d2+mRnV0dXJlksQGc3lzdGVtxAN0d2+oQ2hhbmdlT24A
  init.sh: |

    # Copy readonly config files to real config files
    mkdir -p /root/.ndau/ndau || echo "failed to create /root/.ndau/ndau"

    # write messagepack if not there
    if [ ! -f /root/.ndau/ndau/mock-chaos.msgp ]; then
      echo "writing messagepack file"
      cat /root/config-ro/mock-chaos.msgp | base64 -d > /root/.ndau/ndau/mock-chaos.msgp
      echo "This should be the same base64 reencoded"
      cat /root/.ndau/ndau/mock-chaos.msgp | base64
    else
      echo "not writing messagepack file"
    fi

    # Show what files are there
    find /root/.ndau

{{ end }}
