apiVersion: v1
kind: Service
metadata:
  name: {{ template "ndau.fullname" . }}-ndaunode-service
  labels:
    app: {{ template "ndau.name" . }}
    chart: {{ template "ndau.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ndaunode.service.type }}
  ports:
    - port: {{ .Values.ndaunode.port }}
      targetPort: {{ .Values.ndaunode.port }}
  selector:
    app: {{ template "ndau.name" . }}-ndaunode
    release: {{ .Release.Name }}
