apiVersion: v1
kind: Service
metadata:
  name: {{ template "nodeGroup.fullname" . }}-ndauapi-service
  labels:
    app: {{ template "nodeGroup.name" . }}
    chart: {{ template "nodeGroup.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ndauapi.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.ndauapi.port }}
      protocol: TCP
      name: http
  selector:

    app: {{ template "nodeGroup.name" . }}-ndauapi
    release: {{ .Release.Name }}
