kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: noms-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tendermint-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
