# This values file is applied to the helm chart templates.
# You can supply overrides via the commandline or provide them
# in another yaml file with the -f option. Please take care in
# supplying properties of objects. Your supplied overrides are
# not merged, they are overrides. For this reason the `--set`
# flag provides the dot notation for changing a single property.

ndaunode:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/ndaunode
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    size: 100Mi
  port: 26658
  service:
    type: ClusterIP
  chaosLink:
    enabled: false
    #address: "" # http://host:port

ndauapi:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/ndauapi
    tag: latest
    pullPolicy: IfNotPresent
  port: 3030
  logLevel: "info"
  replicas: 1
  ingress:
    enabled: false
    host: '' # e.g. ndau.api.ndau.tech
    annotations: {}
  service:
    type: ClusterIP

ndau:
  enabled: true

  redis:
    image:
      repository: redis
      tag: 4.0.11-alpine3.8
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 6379
    service:
      type: ClusterIP


  honeycomb:
    key: ''
    dataset: ''

  tendermint:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/tendermint
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      # These ports are only used internally within the pod and between services.
      p2p: 26656
      rpc: 26657
    nodePorts:
      enabled: false
      # Node ports from which the tendermint service will be accessible externally at the kubernetes node's IP address.
      # If they are not provided here or set with the commmand line, a random port will be assigned between 30000-32767 by default.
      # p2p: 30000
      # rpc: 30001
    persistence:
      size: 1Gi
    service:
      type: ClusterIP
    moniker: anonymous
    createEmptyBlocksInterval: 10
    persistentPeers: "" # Tendermint's persistent peers separated by a comma.
    updatePeerAddresses: false # Trigger an update for the tendermint peer addresses.

  noms:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/noms
      tag: latest
      pullPolicy: IfNotPresent
    persistence:
      size: 20Gi
    port: 8000
    service:
      type: ClusterIP

  # deployUtils is an small image with tools used for small tasks.
  deployUtils:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/deploy-utils
      tag: 0.0.1
      pullPolicy: IfNotPresent

  # default configuration for tendermint's priv_validator.json file in base64
  # This should be supplied in the commandline.
  # What ever value is supplied for app_hash here or the commandline gets overriden by the tendermint deployment init containers.
  privValidator: eyJhZGRyZXNzIjoiRDBFQThGODk5N0FGRkMzMzkzQTAxNTk1OUIwQ0VENDdBRkNDQTU2RSIsInB1Yl9rZXkiOiB7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MCwibGFzdF9zaWduYXR1cmUiOm51bGwsInByaXZfa2V5IjogeyJ0eXBlIjoiZWQyNTUxOSIsImRhdGEiOiI0MzkzMUQ1Q0FBNUQ3QkRBODY4RkI1QTc5RjkyQTQ1QzRERTRDODYwMkI0NUIwQjM4QkQ3RTRBQ0FDNzYyNDVDRjE0Q0UyNzNBRjBCNTg4MDJERURGNEFFRENFOEI2MUUwNjAwODgyMUFFOUFBRTVEQURFNjcxMzYwNDI2Q0U3MCJ9fQo=
  # The json below (minute whitespace) is base64 encoded above.
  #  {
  #    "address":"D0EA8F8997AFFC3393A015959B0CED47AFCCA56E",
  #    "pub_key": {
  #      "type":"ed25519",
  #      "data":"F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    },
  #    "last_height":0,
  #    "last_round":0,
  #    "last_step":0,
  #    "last_signature":null,
  #    "priv_key": {
  #      "type":"ed25519",
  #      "data":"43931D5CAA5D7BDA868FB5A79F92A45C4DE4C8602B45B0B38BD7E4ACAC76245CF14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    }
  #  }

  # default configuration for tendermint'e genesis.json file in base64
  # This should be supplied in the commandline.
  genesis: eyJnZW5lc2lzX3RpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImNoYWluX2lkIjoidGVzdC1jaGFpbi0zRUFMNzAiLCJ2YWxpZGF0b3JzIjpbeyJwdWJfa2V5Ijp7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwicG93ZXIiOjEwLCJuYW1lIjoiIn1dLCJhcHBfaGFzaCI6ICJmNWQ5YmM1YzM1OWZmNmE5ZTIwYjkyOWYyN2U2NzUzYzQ4OGMxODYwIn0K
  # The json below (minute whitespace) is base64 encoded above.
  # {
  #   "genesis_time": "0001-01-01T00:00:00Z",
  #   "chain_id": "test-chain-3EAL70",
  #   "validators": [
  #     {
  #       "pub_key": {
  #         "type": "ed25519",
  #         "data": "F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #       },
  #       "power": 10,
  #       "name": ""
  #     }
  #   ],
  #   "app_hash": "f5d9bc5c359ff6a9e20b929f27e6753c488c1860"
  # }

  # default configuration for tendermint'e node_key.json file in base64
  # Don't use this. This should be supplied in the commandline.
  nodeKey: eyJwcml2X2tleSI6eyJ0eXBlIjoidGVuZGVybWludC9Qcml2S2V5RWQyNTUxOSIsInZhbHVlIjoiMjNNZFNycEVSeHo5Z0lTK1JFSmpHbThhTjdzYktLT1p5YWRYSmt4REtHWW9JckpwUkJnOVYvUzRFditCSHNNS29aaTFNSGE0aVdJcUtjWmFwS2ZiN3c9PSJ9fQ==
  #{
  #  "priv_key": {
  #    "type": "tendermint/PrivKeyEd25519",
  #    "value": "23MdSrpERxz9gIS+REJjGm8aN7sbKKOZyadXJkxDKGYoIrJpRBg9V/S4Ev+BHsMKoZi1MHa4iWIqKcZapKfb7w=="
  #  }
  #}

  # default noms database
  nomsData: H4sICKdZ61sAA2RhdGEubmRhdS50YXIA7VhrcBRVFr7dPY/uOJOXqIkkOGigskuYzPR09zyMj4mAD2JQQnZrKTH2dN+Z6cz0Y/oxk0R+KFsIKCys5RMxosiWuG4ZVyiX3VJRXGHFYuOmRMrihxXjAy0JVoFQgo/bSSQRKaJlhS3LnOrb58yde+8595x7zndn/PVgwikQCIRZ1jfEw4EhHqCZYT5CvmAoFKY5lmHDYV8gGAqHaOBjJ940ACzD5HVkSruaVoyUDqGS5RWxXT99HBqWTJ5lnZF9nOK/EPLXy7wiJaFhTpwO5A9uxDVnjD8d5E6LP+Io/oGJM2mUfuXxZ2JhfzASSwnZBJvJS5LMB7mAKrBpRtbaU4GImRO1jJaLJZhQKKRwiagYCCQlLq3SOVHV2WyYZgLBfDgTCwZDEUaUc+3pRELL5Q2D46JBKyipih6RTDUdi8b0pMGLGstzectM6FokLYZMibWkSHtOCcrt0Vjo/+2NXx/565sWXDN/YnXY+c8wP6X+MwgAJvP/XJC/frzE/fk6xqn/dJhlvh9/OsjQk/X/nNAb5Tso1zWqLEsm4ZChyVMAuDVeh4ppkABzb2hl/rxs5fGvfvPJ1n2vbD/y3L+mVElcEJT5O5x5PmtBNJz0AIq6EU1FLjIhUSSkpazYgnmaXGkopdJmERooibyp6gbldM7Y7yZ5QVAtpIASYRam0CTDkVV0xamoIjQIRS8QmqITlqK7PMADhl6EC3N5cIIAFEaVUhjAvH9CYp9T8K8EjXlwuMEFCDygiAoPOdiZ4AQx36Wb0S6lI2XjlynpvKl3ahmlkIjqhtDZGTHpri6qpFmVjbjg3N4whzf5890JHkVfgAQgnSs8JY1XF3t7GZQJzcgwHJSleWMONeCdshv5CMlNqpABoBRJC2GB10VjEa+nILpIkairxeQzEIDzJUVQZUlJeS+bM09XZScA3izy1Nz49a2aOD1XA0iAV9/711muxc5K8vfxeGMlqHBk0coUie3AOqocVEJVLGOh90ovVkqKls5jm7GFXqyhSDKaVVNKSlAEgLIU7DqHscB/KXB4df/LoAoHpAFzFrzigltQmMsNaJpZKKOwtiAJ2WNQF2JrsGKuAtQ6KCHNKyloxM3qFc2PAA+F7KcOTgHAocAOP0rD8ypzHgOZHrc8GUhRTqPJ3h3u5kVRh4aBA6emSoq/ATBeSxF0KEomFNEWq5eD4ht37UYenA870QIYAWbci7023VdWd3L6TrNoNbtx8Nj/bu+5sKbQpu654sNPrqJeuPa5Z598vLQyVtsi6JJmEsj4AqyqhWI8D3U+BeOp1ms9aEt4vLsnI3Gawue5kJYWEmwqEy10FiJ5GYatTkWmWWiGaSiiQxAxMiLzdTeOnmXdOEjdar+GP596urrxO3Zunvf2ri0LfI/0vly/cVf/S5viv314ZaL+rYvwE4MPHNSeLt3XjfdopmFGoslCho5CiS1oYnuHzmRYupDjzYhVEPhoNKnL6Q4+DPPhUaVtttK2HypdGu2bPVB319Nb3u9rOTrvqWUVfe17L28c7Fh/+B/r1GPX7b3k9W58ZgtJupAjfkcC4rON9u6d5fxQV7FIOnBQniQrpxXnyOqSi3eQ1eXMmJRDY9bscRzyLXUBDHcoIm+5/61/EDvOum9ZmMh/Vf7E5z2z/+7d5MBXT/FdVrvhxwboYbrh0/NqUZ4MVRGUKcRA+cXDHcPHuc0/87aB0fXG8+yX3Ltrxk5P3VeVWz+2Y/HUd8zjo+uN57Sj4vzbb/hwyfZ/JmbMQwa6/+AKHtgz/2o3krFl5lTqbmnBVCQ7Ng1YctPsZ+qQ7Ho+Ubf8piPPPoZk4jsf2bvb8+As150vXvS67fb+bVf9ZVVloz2XHOx56jZtQG2yDyOa8jHiM1Hzo1Y20r4nj/X37rd2bD2Q3RZZCU4eOdqwrn/wj4MnPl59aFW8bvcWV1/q4EezNi6fmlm1lvry1cp3D3cs8ly54dM7vn7ogRVL5x5+SH/00vq9b/Y/UdK8aMnmJa33Ve28+UDvK7dq03rTWO0H++t6W+2bNDVc4YuKv9m2/9Ua4dBNZ6r//vrxbuU/H2PG+/3HhEOn4z/HBSbx/1zQC1jvWfAfjID8meCdRDCAuReNojmqNKcAHfP6hiDdzl8v5rGR3VlZY0M7Dmxwr57mICy6BFSM3BGqp59Ws8i1T54cW7POdA9xYCvIz58frUKI9mU3veev+GLdfxY32QcX/27a0Hf3r2+8J7L+BBIx1DaA4XQtG7tkW6J819+2zt1y7O6a4H/ptbohP/rN6q737H+iiBEV/WdLp0mapEmapF8MfQtpKRhGABgAAA==
     
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaosnode:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/chaosnode
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    size: 100Mi
  port: 26658
  service:
    type: ClusterIP

chaos:

  enabled: true

  redis:
    image:
      repository: redis
      tag: 4.0.11-alpine3.8
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 6379
    service:
      type: ClusterIP


  honeycomb:
    key: ''
    dataset: ''

  tendermint:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/tendermint
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      # These ports are only used internally within the pod and between services.
      p2p: 26656
      rpc: 26657
    nodePorts:
      enabled: false
      # Node ports from which the tendermint service will be accessible externally at the kubernetes node's IP address.
      # If they are not provided here or set with the commmand line, a random port will be assigned between 30000-32767 by default.
      # p2p: 30000
      # rpc: 30001
    persistence:
      size: 1Gi
    service:
      type: ClusterIP
    moniker: anonymous
    createEmptyBlocksInterval: 10
    persistentPeers: "" # Tendermint's persistent peers separated by a comma.
    updatePeerAddresses: false # Trigger an update for the tendermint peer addresses.


  noms:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/noms
      tag: latest
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 8000
    service:
      type: ClusterIP

  # deployUtils is an small image with tools used for small tasks.
  deployUtils:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/deploy-utils
      tag: 0.0.1
      pullPolicy: IfNotPresent

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # default configuration for tendermint's priv_validator.json file in base64
  # This should be supplied in the commandline.
  # What ever value is supplied for app_hash here or the commandline gets overriden by the tendermint deployment init containers.
  privValidator: eyJhZGRyZXNzIjoiRDBFQThGODk5N0FGRkMzMzkzQTAxNTk1OUIwQ0VENDdBRkNDQTU2RSIsInB1Yl9rZXkiOiB7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MCwibGFzdF9zaWduYXR1cmUiOm51bGwsInByaXZfa2V5IjogeyJ0eXBlIjoiZWQyNTUxOSIsImRhdGEiOiI0MzkzMUQ1Q0FBNUQ3QkRBODY4RkI1QTc5RjkyQTQ1QzRERTRDODYwMkI0NUIwQjM4QkQ3RTRBQ0FDNzYyNDVDRjE0Q0UyNzNBRjBCNTg4MDJERURGNEFFRENFOEI2MUUwNjAwODgyMUFFOUFBRTVEQURFNjcxMzYwNDI2Q0U3MCJ9fQo=
  # The json below (minute whitespace) is base64 encoded above.
  #  {
  #    "address":"D0EA8F8997AFFC3393A015959B0CED47AFCCA56E",
  #    "pub_key": {
  #      "type":"ed25519",
  #      "data":"F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    },
  #    "last_height":0,
  #    "last_round":0,
  #    "last_step":0,
  #    "last_signature":null,
  #    "priv_key": {
  #      "type":"ed25519",
  #      "data":"43931D5CAA5D7BDA868FB5A79F92A45C4DE4C8602B45B0B38BD7E4ACAC76245CF14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    }
  #  }

  # default configuration for tendermint'e genesis.json file in base64
  # This should be supplied in the commandline.
  genesis: eyJnZW5lc2lzX3RpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImNoYWluX2lkIjoidGVzdC1jaGFpbi0zRUFMNzAiLCJ2YWxpZGF0b3JzIjpbeyJwdWJfa2V5Ijp7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwicG93ZXIiOjEwLCJuYW1lIjoiIn1dLCJhcHBfaGFzaCI6ICJmNWQ5YmM1YzM1OWZmNmE5ZTIwYjkyOWYyN2U2NzUzYzQ4OGMxODYwIn0K
  # The json below (minute whitespace) is base64 encoded above.
  # {
  #   "genesis_time": "0001-01-01T00:00:00Z",
  #   "chain_id": "test-chain-3EAL70",
  #   "validators": [
  #     {
  #       "pub_key": {
  #         "type": "ed25519",
  #         "data": "F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #       },
  #       "power": 10,
  #       "name": ""
  #     }
  #   ],
  #   "app_hash": "f5d9bc5c359ff6a9e20b929f27e6753c488c1860"
  # }

  # default configuration for tendermint'e node_key.json file in base64
  # Don't use this. This should be supplied in the commandline.
  nodeKey: eyJwcml2X2tleSI6eyJ0eXBlIjoidGVuZGVybWludC9Qcml2S2V5RWQyNTUxOSIsInZhbHVlIjoiMjNNZFNycEVSeHo5Z0lTK1JFSmpHbThhTjdzYktLT1p5YWRYSmt4REtHWW9JckpwUkJnOVYvUzRFditCSHNNS29aaTFNSGE0aVdJcUtjWmFwS2ZiN3c9PSJ9fQ==
  #{
  #  "priv_key": {
  #    "type": "tendermint/PrivKeyEd25519",
  #    "value": "23MdSrpERxz9gIS+REJjGm8aN7sbKKOZyadXJkxDKGYoIrJpRBg9V/S4Ev+BHsMKoZi1MHa4iWIqKcZapKfb7w=="
  #  }
  #}
  # default noms database
  nomsData: H4sICOxE61sAA2RhdGEuY2hhb3MudGFyAO1aC1gU1R4/y7IrKwvxEkQlMUCwbrCP2RciLSKSSaiAr7Jkdnf2PbO7M7O77HYlfCZlWmRX1FLUVCKfqYQPkoxKzQdXvdeyTDTNXhaFpn2a3DPDSOhHGrfydr8833e++Z8z58w58//9/v/z/89uahr4w4tEIlEpFPHsVSVhrxIZ0n7lSrxULlfJlIhMqpTHS6RylVQJ4hV//NYAcFM0SsKtWB1mgjKRGEbYUcJgJW8cB4cZjTd5DvceHdf/k5KaRrgJt0alNqvctNmsJ2xmCrZtOGXAPDLahMt++xpQH0pONV3iL1cpOuEvi5fIpCqVHMRLfvvSty5/cfwnNYmE2Q4ct9D8QByjUREAPZwoiRE0FQSAwIPa3ZhI9DC8AxVAY/yeerPFbijkiREhAEIzZjGZaT4IAiE8pCccbDGgtIOk4L2jy48eGVAmBLwAgd6MOqge5N7YndNGbmirQGn+iWdMK/u8f2FBIG9KxM7W4BTmCVz5t31F88DKjGq897Ma2OSl9v7huT2P5DFywLVHcEMfgzUZ1vDOj1y2cOK/Rs95W9p/fmLKQdk8ksJfbpvjb2Z8CZ+bN7ttywe7EvXfjL6tmv5zltQ0HCUsRoyi/7g1bmX/0Nxv8P8KRK66Y/+3oyDpqlSpOt1jsLpIJ6m2KjSIwyWTG1CjzClzkya9R4Lp9NZ0p4t2uGkXpZJJdCiCKA1uvdNtV+AqK2JwqpXOdInc5jLrMETioTGNQaKxq01Ss1ItI4x2mUSpUKTLVem3OmrS5f9rdfzlSmpa3qjskX/sGoz9I0h34j9Errhj/7elpKbdynB/+xo39/9SuVIuvx5/mURxJ/67PcXTkscH1JytwzAj6rbThRhN2zEchn/D3CRKWxzE9NXZbpKJBysa41/LKJv9eUGOefWht94rXHoQPzvwmVi1ougt5CVBTm55ydLG2GGP5wLtquFu2k1iP0/AZ61acjq0ZQQfNIfebPIv7aE624wSJmwUAT5MfthCwG5BTNFQjPZCtPIdBqwA86KkId+BWwhB3zyqiy0b/TBUXDQW9Ob2drUQpBYCUN3ro4z1eQ69DTMUwOi2CNXZsdd3AXBX+hBQUwMyB4PYCrD1/tEA0+iisgwGEqNqH+eBWF0uqFkFjDkgdoO2ngmfIWXGXYt+B006sBmAOHIkqKkDnhEgdke/arjrQhq11V7kgaBwZU0F6IXETol6LSdrxHBsrzcABMdpaqaDVBWInSXeOJawf8nng/ChDwA4cvgQEFtZtLmIRAkK1TPqGI5hhXrS4qSnrysOBFH5Q0HNElCgBbHLwHZfFW6Lh2OKLDjmcNdWA9DXOgLUrAdELoirzSvA7BhKYcNJB55DGBxeRssH1vDZQetqgTUXxNaCzQMSUnIdDgOBUdRwN5ETXRsSwCxSzSyS+DMY55uogvLghpskELwuo36lFISnlnC5BQBBYtBlhjGJSy865xViIAZ8gVDEA7yQXCDizRmeBc7HwBYf3JKdIlE+imOUE9VjAXwcdQpBCMw7OGQwPhAdhvYQ86Dnc5go/DIXuXEpg9c1wHHBLILtxOGDeQEvTlsBm4fAEBFYXuR4/kMJYSB0cptbZbRRar2VsHhNZoPfj+gwncdtpJSYxmNzmnQyvdXj8qIaM8bNv2uotmO+k0JwF+olzJgZUdt8bjWhKDGqjG6lTebzeRCPBfN4vZiKKNHRuJebz5tVxcwXaDe4DD6Zl1R51Aq5zutBSjyYyko5PUaDgjJ5UUuJxe2nZW7cpFSV4FhIWRg7M6RhA4kqTD69GvG5yBIXTht9pJm0mDG326jwqRErjlp9GpvZQPtdJVZXiPZ8KO/FcmbPDXzApzwWPi+gx5YS7bl7F09cBe5+apepafsxYeypk3we7zMeoHo8e3ERelTzYI6iZmF0zOF6/sEnoml4z9OzORSy8QajZhXfzmiYbAoO8fa8XcaHxIejOvFU3w6PoJFfBWZD84FmdL1l88Ea3sIKiF7Ao08O0YKDEMbA6pjdgOkKrL3qL2O7hFcS1rBdPSKmvNHAdolGpz3HdonwKxcA2xX8ymCa7Qre83dZ+7NCLuVOYLtCEy87ygAvLywsrzAD8DRRYWX+NQ2AFymOqJocL4gMi/joxy+BIFIcdd4WCJu9VL5krSByzAsgX9QWhOU7pOEp7c6G4gP580lftmQ7aYpWa4xem0yDWRRep8FaQiI2hczrQmm126tHNRojiZtLUBXmUUEFdmXnmUWg2WZROgnUo5Q7zXqdwmTTeH1etQfHVG4fgcsUGK2SYQaNn1BTNgPCB3Edvg3fF9Vu95njQDOKKTGfTqk3ePwkDUeXmJw2mCBYoIWQPqeN8Oo0JKX3+dS0zO/ng7s6PKz0zcDiFweMBD0UC8QBRcGnk9RhrLKS1EEQiUFNYf3WzYlsFkQGQRAGNYk1j/VOHjRDzKhfoAkbB3VeJRgIggc0VUH0u3KIfCBsDKwCfSD83EExM7o3d1BoFt+/tjccDHUqmirTRsUdLQZBFOZyY4QeUiOo/FgQBL+8LS7ihi8ZWcOGNl73JePx6m8bH/p02aDXd5/Zf/J45iHLpxd0gQEfCFZohVHt7E9I3hEh/hvnKtiVep1I+yxmwi+Qtli6eEo/+828TmWbvCb+750B4TbYDgrHltbljYLV/DohCOwO/XmRYSz7IRNZ7sM2S31IUFbzkWEs7WGTIT1sspSHTYbwsMkiCJsM25kLJLsoj6O6mKE6bLUzXcwwXZTX4uK8bJc07cR81v3915S9TkOQti26bvKWoxALQNfRBnuL6ozzwqYLWzWVQuZAuvV0QV/JdZPDZ5yZMY/XMlcIAm4FdYd6bsM7bflEW/ceQyvBHVp1Qatp3YTgV3qubkEU498OdgRCiIS3ESIxAxFE4c+OUEO3z6tMOw8eVMocHntKCT7T9AeB0tL20ykpR1HafjLJFKXXDqWk0pbs3wPZGz3CE6NwnvJIh0q6FQbsPNS49t5Xfj2fLu69GnE3fXNw5k4e/x57jHX1piasX/ULAS3Df6dAWKANgmFwL21dNwNgOA8Gsb26Gfo+pAWfdyvm5V6Qi3obLk3OZ49wTqHYzyrmVHfhgZ1H2F86rmUcZ2YVRUQM6xwetVvrN6aD/fRQx8UvXh+FMlRkTPSaY2RMGNokFzKJGQuGF4aZIg1nv2qWnj8HrF/jF5YH9bsWQqeEZZxxtmQIAf/XJzw3huaChM3dC8zH2E5/EpXXlZcyXFpLb+BNurWz4l715r5KzPgq6ICuO00Gcr4qjI3IBZFdOis1G4+zC7PuKnRqhelwQB2rpj/z8fcc51z/PIGDMUGwk6Ubi3z5F4HTOoJilk6X9l2uF8V3OMjXDr3h7xjAvkzYjv1fJcz+Fbm93oK2sb7rJpnjicxHQjv50m4dL9Ozf+gTilyf72sD1vs7Pa9b+tz6UD3E/szS00/Pmg9fNrRPj4HnbEuz1azmrhjG8HtmfQPl6P7S4BHPDn35Wyj3SOnzady9s/e9BOWeknfHJ/5ozTRBOWHw18OcPxg/f5VJVIc9nXdPog0XMenow053yHnFM37G+PNnz904MPpyI8PO0f/csmjWj/s/gPKAMfvn1738yaIvmLy3oLo1Zk7lv5k9xF5LcRi3U3xsfFrW4jHML7T98cJVWVlTvhwH5UhiSfOiuISNzB8EervWxOfUbn7SDuVE1097jh3fllQH5TDq0SeWrMyZfRzK8SVfjH2ituDSFShHXEv/ocx7bu6pyT2Ljq9mQK8g+mIL4pa9CeV+i5PmDTm1rDezB/H6kZc1E8mDV6EctL4+L6VMuisayvdsTm1KdseXx0BZ0PG5AZZ9wseXEcjyd6AYd2D7PO8kddkWKPNPmB8jF11RnoFyr2bjqAbDq5+UQrlP68WGfFdsQV8o9714bt60Se+M3A7l8J9Gvi/a3XpvJpTvvvpd9kFDvojR1V2wWuDWj0J1ngXtv0KLmfdi1mP2BetAeH86vA6BdQGUV8DK6DwDVubLdiI39go3PpzRI6yPMnyA1c3sC9ZKOC+d64vg1maug7hnMM+LYq+dPrN0/qzSOU0Nm+VYuLSoNmP3x1Ufplbkt9230T6h1IrE/PTDuy89PZXUvH/41fLMaunMiSMT7rlMu77Ks56yyJeURZUp3r5v4n0lH2d8ParGXDkzZsmSl7KqJoSnF60YVVrp7TlqyoBWU9kzFxRZGy81PSms9/+j8DPhpoctG4pXPtmzuPXDva0Dnhq3+1SC34CvXaifPeDbTXvfKfjOtCX1cOLZKwtkQ+4vGWGXF18KOfnGhHpN9KvbJlPPr5wcevSRx4r2z3/kzRkAGM+NW4+0HZy5rcpg5S9FxKd2ZIdoryTVidLGJMRtWn8GQd6c1LIw6vK51U0W3tY+85TVD3hLAb5mbvy0s9vU696WIM5TE1Mlc6a8m/VFf7dt8PHqqTOXf5/aOn2scur4Tdj288PmJx8pI89//MqMRfXRheuSV4w4vbR6bbV4Q9Ce3LFTJp98KvLlYvz8jrnfnjpwtg7b9t24ddvObJCPUJaerm9943LIgZWv/+ujB1uXDz65a/xc0742pPGnF1Yt8kWEbEo+wc+tWO36rpLkqdYpVmzOOZEStmYWeuTuC9OaygOOfp9wLLv842qIX1L7B/k+EXf+nXCn3Cl3ym0p/wHMeyKGACoAAA==
