# This values file is applied to the helm chart templates.
# You can supply overrides via the commandline or provide them
# in another yaml file with the -f option. Please take care in
# supplying properties of objects. Your supplied overrides are
# not merged, they are overrides. For this reason the `--set`
# flag provides the dot notation for changing a single property.

ndaunode:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/ndaunode
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    size: 100Mi
  port: 26658
  service:
    type: ClusterIP
  chaosLink:
    enabled: false
    #address: "" # http://host:port

ndauapi:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/ndauapi
    tag: latest
    pullPolicy: IfNotPresent
  port: 3030
  logLevel: "info"
  replicas: 1
  ingress:
    enabled: false
    host: '' # e.g. ndau.api.ndau.tech
    annotations: {}
  service:
    type: ClusterIP

ndau:
  enabled: true

  redis:
    image:
      repository: redis
      tag: 4.0.11-alpine3.8
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 6379
    service:
      type: ClusterIP


  honeycomb:
    key: ''
    dataset: ''

  tendermint:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/tendermint
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      # These ports are only used internally within the pod and between services.
      p2p: 26656
      rpc: 26657
    nodePorts:
      enabled: false
      # Node ports from which the tendermint service will be accessible externally at the kubernetes node's IP address.
      # If they are not provided here or set with the commmand line, a random port will be assigned between 30000-32767 by default.
      # p2p: 30000
      # rpc: 30001
    persistence:
      size: 1Gi
    service:
      type: ClusterIP
    moniker: anonymous
    createEmptyBlocksInterval: 10
    persistentPeers: "" # Tendermint's persistent peers separated by a comma.
    updatePeerAddresses: false # Trigger an update for the tendermint peer addresses.

  noms:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/noms
      tag: latest
      pullPolicy: IfNotPresent
    persistence:
      size: 20Gi
    port: 8000
    service:
      type: ClusterIP

  # deployUtils is an small image with tools used for small tasks.
  deployUtils:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/deploy-utils
      tag: 0.0.1
      pullPolicy: IfNotPresent

  # default configuration for tendermint's priv_validator.json file in base64
  # This should be supplied in the commandline.
  # What ever value is supplied for app_hash here or the commandline gets overriden by the tendermint deployment init containers.
  privValidator: eyJhZGRyZXNzIjoiRDBFQThGODk5N0FGRkMzMzkzQTAxNTk1OUIwQ0VENDdBRkNDQTU2RSIsInB1Yl9rZXkiOiB7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MCwibGFzdF9zaWduYXR1cmUiOm51bGwsInByaXZfa2V5IjogeyJ0eXBlIjoiZWQyNTUxOSIsImRhdGEiOiI0MzkzMUQ1Q0FBNUQ3QkRBODY4RkI1QTc5RjkyQTQ1QzRERTRDODYwMkI0NUIwQjM4QkQ3RTRBQ0FDNzYyNDVDRjE0Q0UyNzNBRjBCNTg4MDJERURGNEFFRENFOEI2MUUwNjAwODgyMUFFOUFBRTVEQURFNjcxMzYwNDI2Q0U3MCJ9fQo=
  # The json below (minute whitespace) is base64 encoded above.
  #  {
  #    "address":"D0EA8F8997AFFC3393A015959B0CED47AFCCA56E",
  #    "pub_key": {
  #      "type":"ed25519",
  #      "data":"F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    },
  #    "last_height":0,
  #    "last_round":0,
  #    "last_step":0,
  #    "last_signature":null,
  #    "priv_key": {
  #      "type":"ed25519",
  #      "data":"43931D5CAA5D7BDA868FB5A79F92A45C4DE4C8602B45B0B38BD7E4ACAC76245CF14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    }
  #  }

  # default configuration for tendermint'e genesis.json file in base64
  # This should be supplied in the commandline.
  genesis: eyJnZW5lc2lzX3RpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImNoYWluX2lkIjoidGVzdC1jaGFpbi0zRUFMNzAiLCJ2YWxpZGF0b3JzIjpbeyJwdWJfa2V5Ijp7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwicG93ZXIiOjEwLCJuYW1lIjoiIn1dLCJhcHBfaGFzaCI6ICJmNWQ5YmM1YzM1OWZmNmE5ZTIwYjkyOWYyN2U2NzUzYzQ4OGMxODYwIn0K
  # The json below (minute whitespace) is base64 encoded above.
  # {
  #   "genesis_time": "0001-01-01T00:00:00Z",
  #   "chain_id": "test-chain-3EAL70",
  #   "validators": [
  #     {
  #       "pub_key": {
  #         "type": "ed25519",
  #         "data": "F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #       },
  #       "power": 10,
  #       "name": ""
  #     }
  #   ],
  #   "app_hash": "f5d9bc5c359ff6a9e20b929f27e6753c488c1860"
  # }

  # default configuration for tendermint'e node_key.json file in base64
  # Don't use this. This should be supplied in the commandline.
  nodeKey: eyJwcml2X2tleSI6eyJ0eXBlIjoidGVuZGVybWludC9Qcml2S2V5RWQyNTUxOSIsInZhbHVlIjoiMjNNZFNycEVSeHo5Z0lTK1JFSmpHbThhTjdzYktLT1p5YWRYSmt4REtHWW9JckpwUkJnOVYvUzRFditCSHNNS29aaTFNSGE0aVdJcUtjWmFwS2ZiN3c9PSJ9fQ==
  #{
  #  "priv_key": {
  #    "type": "tendermint/PrivKeyEd25519",
  #    "value": "23MdSrpERxz9gIS+REJjGm8aN7sbKKOZyadXJkxDKGYoIrJpRBg9V/S4Ev+BHsMKoZi1MHa4iWIqKcZapKfb7w=="
  #  }
  #}

  # default noms database
  nomsData: H4sICEAu61sAA2RhdGEubmRhdS50YXIA7VcLbBRFGJ7de3S33pX2eLXaYtFKitbr3d7e3l2tkqs8NFQgFDSYKM7tTu/2Hrt7+7hrC1GEKKAolSggjwZDMbZqxAhBYnj5oKgJVolIjBpSgShEigQEBR9zbaW1Eqsxxaj9srPz7+3M/P/8//7fP+csB4MOl8vl83qLu3qfq6t3MWx334Nit8fjYziGY/ELlxvLLlDsHXzTADA0HarYlKgckbSwipAUh5IQVfuPw8Nqa/9gnZ59XOr/JXCWJ6Ak1iJNHzwd2B9cj2suG3/GzfWLv5dlcfxdg2dSL/7n8WcrfE63v8KvKQxKMQEXCvkMOSqmvDGP152AbjWupJIxf0U8JClJVvZJHMujmMcIpZIwFI2HOA0xckpzVQT83rDulngUCsclXk348TiRTwUkN0QJ1eOp8FeotRoUFC/kUoYeUhV/RPDootcQ/dGk5E5EAxWef9ob/z84y6un3z51cHVk8p9l/wr/sx7OPZT/VwLO8oGy8u/rGIj/WZ/nt/HHBYHlhuJ/JbCNaKett8uJhKibzAmkQxqALAWqSNI1CgBLCsYNRNN34TfYAzoyZfMRMS7UEDaKtmhE1qwsCvK8bODhVgBoAcVRGA8j7MXmuKRKJkABO2GzSLJgKSgxSWqaBCZFUovGmE0GMwzkWyNIDEf0orFsNlYlClCX1cxK1PLmi8XzrYAgzZIAjax1s9mnFi45/+P441sO7tl+5tU3RhSKZmIx9e1rV5VmlPTgYHzjYWf+d43v3lud+XDJX6d1vXtmTdXj/jUXsEjgtg63cbjl9V1ybsjR9vKWSS3nHitxf8AsV7XE+p+XNRzOnERNPSo6ft566M0S/uSMKxypwYGzfKDC/fd1DJD/DMf5+ue/x+cZyv8rgfccu/8g/4nL5h2uzXnOuh5qwKlqA5cliOqe3O6T2LTFcsOhXsa4RBdaF1lkWAJpGZLIUITJkFSrDdhA181kJaw20mQCNEHn0gQg7E9i8YCFdy4BVSlwqtIKTKRLEiSIOFQf4ngh1aDqgQapLqzElKQuqlBX65WYlA4FVI2vr/frTEMDPWyanNCCvGV75USow+FZIYijzyPMKPRiTCo59nZWlKVp2C4S5EWgNpE+Yh+xD7sIy9UyHwMgF0szURqqgjYLqmGE/0dR+KcaHcYQAMNFiZcTohS2Xz9xsionLADY49hRk4J3zlaEsckSTF1kUaMl/EGzpYC6JxisKgD55jhemaaI3URdoZkOyZKhzbTfZidyKcFQIbGJmGknKrNFbZqsi7UiEjDvGhJxh1mb7rwOmO2qcxcoJAGloaSBuJHEDIeGdD2OEjimNVjC1mj0KOIJIofLB6Vmmo9AKYy0oF60eNpaYKOx9fTXIwAwS6jOiXPwqoKkTcOGBw1bDJcCi1ad2RuZBQVBRZpGAosii5KzErB2AxMIEkQdCXiDRY+AnLva9mH/TUX1eAHCBG5YQbw9tjiv7OLYt/TsZd4Nnec+mrd5VEl6rvz+rceOT6C3TXn1lebncgsqSmt4VVR0zLmONCosRUIwhVQYRsGwcwoJyGDT5pjIKRJMcR4lwoe84VggXZ/2pxLIZ9RLCcaLdB+DBBx/vxYT2J+aSHwtbCLBS/dnbt3Pl66GJnLBW5smf9zWMr14bfuu8g1tHTs3Bm98dkmo/MPR5IXOlV8rrbkHm8jNiq7p/kBtOsYEkOhNK0K0TmVjXiadhLrfSPMwEKhVE5E66EMpX6/SlozSlt8rnR84cPORskdbW748UHN28gsL8w9E999S1Vm35tTrjfK5O/Zfu7eJHFdDUbgeOu6mgOn7DcDigF3POQJlJoGjlioYk5OkioZdvZsqcvSrobZvljf2raFzHmsRz5W99t0oJfTU8Q0jdx4tiOlmclZ264nSdX82Ns8ylSe6K273Z9vySdsxb+/0gbz4A/fpE32nN0c6W4/1Th/IH2eFqfP6Tn+pgzs9/tdtZejs6fMzT8+7dhfEYtbKmpG+w+M+y9R609oV8y9OHj1hPZYtrZ3rh2dtX9KGZeL9VTdZH94xei+WzR1bJzy/tKDqGixbOze/8IByRK7GMomnHwbdZwUnbnn9+77unPHg3DOb9r/oKyx7aMHZysaOzkWdF75adnLpqlU7VkTvW33+Ahessd227sSCn1avXDx/0qlnTi58Z07k6Le87eO1ypj2CFF69FBZ+2zPoo2ORV8Ypz5n7t/TjHX0nG+yTf+ps8cQhjCEfxa/APPQrr4AGAAA
  
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

chaosnode:
  image:
    repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/chaosnode
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    size: 100Mi
  port: 26658
  service:
    type: ClusterIP

chaos:

  enabled: true

  redis:
    image:
      repository: redis
      tag: 4.0.11-alpine3.8
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 6379
    service:
      type: ClusterIP


  honeycomb:
    key: ''
    dataset: ''

  tendermint:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/tendermint
      tag: latest
      pullPolicy: IfNotPresent
    ports:
      # These ports are only used internally within the pod and between services.
      p2p: 26656
      rpc: 26657
    nodePorts:
      enabled: false
      # Node ports from which the tendermint service will be accessible externally at the kubernetes node's IP address.
      # If they are not provided here or set with the commmand line, a random port will be assigned between 30000-32767 by default.
      # p2p: 30000
      # rpc: 30001
    persistence:
      size: 1Gi
    service:
      type: ClusterIP
    moniker: anonymous
    createEmptyBlocksInterval: 10
    persistentPeers: "" # Tendermint's persistent peers separated by a comma.
    updatePeerAddresses: false # Trigger an update for the tendermint peer addresses.


  noms:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/noms
      tag: latest
      pullPolicy: IfNotPresent
    persistence:
      size: 4Gi
    port: 8000
    service:
      type: ClusterIP

  # deployUtils is an small image with tools used for small tasks.
  deployUtils:
    image:
      repository: 578681496768.dkr.ecr.us-east-1.amazonaws.com/deploy-utils
      tag: 0.0.1
      pullPolicy: IfNotPresent

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # default configuration for tendermint's priv_validator.json file in base64
  # This should be supplied in the commandline.
  # What ever value is supplied for app_hash here or the commandline gets overriden by the tendermint deployment init containers.
  privValidator: eyJhZGRyZXNzIjoiRDBFQThGODk5N0FGRkMzMzkzQTAxNTk1OUIwQ0VENDdBRkNDQTU2RSIsInB1Yl9rZXkiOiB7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwibGFzdF9oZWlnaHQiOjAsImxhc3Rfcm91bmQiOjAsImxhc3Rfc3RlcCI6MCwibGFzdF9zaWduYXR1cmUiOm51bGwsInByaXZfa2V5IjogeyJ0eXBlIjoiZWQyNTUxOSIsImRhdGEiOiI0MzkzMUQ1Q0FBNUQ3QkRBODY4RkI1QTc5RjkyQTQ1QzRERTRDODYwMkI0NUIwQjM4QkQ3RTRBQ0FDNzYyNDVDRjE0Q0UyNzNBRjBCNTg4MDJERURGNEFFRENFOEI2MUUwNjAwODgyMUFFOUFBRTVEQURFNjcxMzYwNDI2Q0U3MCJ9fQo=
  # The json below (minute whitespace) is base64 encoded above.
  #  {
  #    "address":"D0EA8F8997AFFC3393A015959B0CED47AFCCA56E",
  #    "pub_key": {
  #      "type":"ed25519",
  #      "data":"F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    },
  #    "last_height":0,
  #    "last_round":0,
  #    "last_step":0,
  #    "last_signature":null,
  #    "priv_key": {
  #      "type":"ed25519",
  #      "data":"43931D5CAA5D7BDA868FB5A79F92A45C4DE4C8602B45B0B38BD7E4ACAC76245CF14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #    }
  #  }

  # default configuration for tendermint'e genesis.json file in base64
  # This should be supplied in the commandline.
  genesis: eyJnZW5lc2lzX3RpbWUiOiIwMDAxLTAxLTAxVDAwOjAwOjAwWiIsImNoYWluX2lkIjoidGVzdC1jaGFpbi0zRUFMNzAiLCJ2YWxpZGF0b3JzIjpbeyJwdWJfa2V5Ijp7InR5cGUiOiJlZDI1NTE5IiwiZGF0YSI6IkYxNENFMjczQUYwQjU4ODAyREVERjRBRURDRThCNjFFMDYwMDg4MjFBRTlBQUU1REFERTY3MTM2MDQyNkNFNzAifSwicG93ZXIiOjEwLCJuYW1lIjoiIn1dLCJhcHBfaGFzaCI6ICJmNWQ5YmM1YzM1OWZmNmE5ZTIwYjkyOWYyN2U2NzUzYzQ4OGMxODYwIn0K
  # The json below (minute whitespace) is base64 encoded above.
  # {
  #   "genesis_time": "0001-01-01T00:00:00Z",
  #   "chain_id": "test-chain-3EAL70",
  #   "validators": [
  #     {
  #       "pub_key": {
  #         "type": "ed25519",
  #         "data": "F14CE273AF0B58802DEDF4AEDCE8B61E06008821AE9AAE5DADE671360426CE70"
  #       },
  #       "power": 10,
  #       "name": ""
  #     }
  #   ],
  #   "app_hash": "f5d9bc5c359ff6a9e20b929f27e6753c488c1860"
  # }

  # default configuration for tendermint'e node_key.json file in base64
  # Don't use this. This should be supplied in the commandline.
  nodeKey: eyJwcml2X2tleSI6eyJ0eXBlIjoidGVuZGVybWludC9Qcml2S2V5RWQyNTUxOSIsInZhbHVlIjoiMjNNZFNycEVSeHo5Z0lTK1JFSmpHbThhTjdzYktLT1p5YWRYSmt4REtHWW9JckpwUkJnOVYvUzRFditCSHNNS29aaTFNSGE0aVdJcUtjWmFwS2ZiN3c9PSJ9fQ==
  #{
  #  "priv_key": {
  #    "type": "tendermint/PrivKeyEd25519",
  #    "value": "23MdSrpERxz9gIS+REJjGm8aN7sbKKOZyadXJkxDKGYoIrJpRBg9V/S4Ev+BHsMKoZi1MHa4iWIqKcZapKfb7w=="
  #  }
  #}
  # default noms database
  nomsData: H4sICEAu61sAA2RhdGEuY2hhb3MudGFyAO1ZC3gTVRa+0zRpQ1PokzZAsVj6cME+ksmrQkkpbUFqgT54KCydJJP3TJqZSdIU0PKw2wICVtCKIgVXKLECBSxvqFJRVGhFFGVxiyysrwWLgOK20r2TpFigvGRxd7/lft/95tyZe+7j3HP+/+QmMQnc85KcnCyTSKLdT1my+5ksQj1Pb4lOEYtlIqlIIhWj0ckpUBaBaMm9XxoANprBKLgUo0VP0joKx0kzRmqM1LX9YDet9ibjePdx5fk/UhKTSBtpU8jkepmN0evVpElPw7aJoDW4XcToCNHdzwHtIfWapsfzF8skV5+/SATfgujku5/61uX//PyntvB5GRaCMDAcXwJnMD4AfsUYhZMM7Q8A146ZbTif/xj8Ag3A4Jxear3BrMlHBCgPAJ4eN+j0DAf4g0AE7QU7GzQYY6Fo+O3o6qNHBpXxAOLDVesxC+1HvS/cO2fsxs4qjOG0LtC91u+Diy/4IrNC9p4PSGBH8JZPza+eiKseVktEPqOATSQx8sclBx7PYWWfriG8XafBGg9rcPchV7045ZPxC/elPLB0cEKzaDFFEys6F5aeYLGE49Wr6Hzzs7cHq8+O/10t/d9ZEpMIjDRocZq5d3PcKv5FKbJr8F+CouL78f97FDRVlpgiTzWhelRhVaXQOrnKQtAGq1WbbC42WFW02qoSY7pUxqS24jY8GaclOKo2oTITRolMGgWBklKrimFSi02kSKPX2u1qrY2RqCT6FBNF2VRWmkmWMHaTPFUsTb0V1aSK/9Pm+L8riUk54zLG3ts52PhH0TvJ/1Cx9H78/y4lMelWgXv3c9wc/1NEYqnomvwvRSa9n//9LsV/AAdwm3xrQPS2GRMG+Qo4AKnYnrcw9sU+NRywrM/Cz+MfM5CjbBTGGCzkSJxxQAPlWjR4Hu7AKE2uhTCQGNJ/Gz13bYaNYtPGqqbo14eVVXydl6lfe/itd/NXNhNfxS0QyiUFb6EvczOzK0tWNsUvLwSRa7JsjI3CL+eDxHxgrs3QY6QOH0eC+kLSbFGbcE0ezDcLMJUZ39QEc7yRI4BrPcgaDoTVvhtyvn0egD6pw4FrKUh7BAirwPaHvwa44p9h6RoNhdMNPyJAqMoGrjVAmwmEG8FOYW0gPRhuocBA4BYbs+kUAvobxwDXFkBmA2ED2IIQQ7MtFg2J03SWjVQjDZs2ABCWOxK4akGeEghXhb2emT4mC39/CAcERClci0GiDAjLI7cUUBhJY7EDB2TheL6aMhQ3fIp4FKs9isrdbIINnWpiV35cSR0ScUAUNRa4NgP7GCDcNaAWmjmfwUwNAVzgHyx1VYFwVDhr/M483IxjNJ5FWYhMUmNxENDEh2Texb/qWTy6fRSuxWxmJh9nGDOObD6XBOauD/Vzm2DkJnD8YN7o9DYlB6Td+EiEVw3BztJ16L+ezFJu4d8rkbYKHvDhgDDPvtVsl66dMxzEx8915vWTuTMczXie3Tj0zVWfH2o+fIqDIL0A129o+L5jG1+f8NKj07alLR8i8z2TtHcr/OQDEA64DT9jP9EcwP8Y+m1Y1NEi8LcfLvheRtrSeIDDAX1yrvYaDihaVgW7+oXM2toImqGOT0HAKcC+6j243VLmfuVbG/EeQOKCBqxfGHqCGyrgdcTUceMEimmR8XyFgD8+aQk3NGhiwJ8fqeHGtc2HTwb8d2w9T4CYlvDaDvDYAW4ZcXx+LkbgdDGmxn04BFbMA3z4k8vrcrh33IjR9q/h7vr3NLc3bCBWHEYO7CuDNmB7dQ8YthcLJZwaUMEBwdcFMQfUIS+yxvd54qnhyl+Nz77ybbhcWsYNRVnrgytnBo/DewB8ouMigE3W/rAZcGCmSAmbgZeyJ8Om+zRhMygnfxj7KCut4+cIQmqmR8NWyF9+/ha2wi6YfGErXOaM5+f4RoyO5fsLcy3czkjcs9tBwW2FHuiAVhY/+3kyqSGLGZqRK7QOk0iBGySOYo2xhEJNEpHDijFym0ONKRRaitCXYDLcLoPhfG2Ue+ImbSJoxHAp7lRJ1Rp7KcUoSskSXbGp2MoY4JFTTsi/DpWCotVOp5wRlZaynpxmRPyh94oyEAHrtNxTiijgmzLT46axyZKZbg99CApdzhk7s23yPfPMTCLS65cKR5DbKbj9Baw7ptcVub3Rn8atNpxU491+yNPTeOVzBY03uV5AerwTkKaA4MQS780DJCgB6PH+Yar38qH7rYMACACHy+MjAAnMBnxkYVY6uBCBsHD1G0JEcMMQuTFYevslPLK+EfYLcDNGl/8v9lk251XYPAyG88HqAovHy1Rik02mNdFytZE0OHR6TWkpqsJVdpuWluIKu6lYpxKpjXarA1Poca9+n5HKK/rFNEpYMQepx/Wo3OS0yUlJiVamtUlNIqfTjtoNuN3hwGVkiYohHF59pLyG1ecqN1o1TpGDktnlErHKYUdL7LjMSBfbtRoJrXNghhKDrZQR2QidVFZC4IFlQW7NwMaNFCbROdVy1GmlSqwEo3VSesqgx202rcQpR40EZnQqTHoNU2otMVoDlUXLKtkVN16PLrGjRl2PLUhczW1DS6y5oGdgQUKDvLjiQfXQoJuiioBFFYgUHlARsKACW7eNKRPyAjsBjnz3UHBCNxyJXdeWcYcw0r8nxk8rACdMBmkxidml4mK9WiXRmRQOp0NuJ3CZzUkSIgnOyES4BoKLnDZp0O5wRCwIuxso2oP4Fi0b5FK84IaiWLnCKmnxApFL0uIBonnwVRcQtURfwaHMsW2T7xlBZh33cWPQ7EHK6zCo8kANe90XHfuyXR0zr5yKXzBy8bp3B+7PzXtHHDr/+61LBhdmSZ8pf5ANeqnLNxLOwaHtBmTvZzJuneiD7RPnN3w0zjTsgUvqbUPzdsJluAbCZNjv4Xkn/XdmBBzdkd2wZ0pha92c+lnH4cc0n7TcBQDw1jmjVlxzCzrZMnzrVbegyyQtsnQxV/jcE42p9IxTytbPzi339fl8OzI24kb4rcMH1D6PtC1zZzl3Rdo3oKhrie+OfOToPPHLYTk9Mb7m0huMYGh3RLz0Yftu6ZHfNs/2R3dfHGC+GfZWd4pdA5mb26I17fHeIaOuTxbP6poHdFvZHcXs3sNNb3TTvaM4nZvxYz9emMf7YuJ3hUTPvNUpnV/dxFVPvkFyi/yaDbEYCEHuqsQ29OrEVu4OWbe2O7P9B3FxdW/0atpS+mwo/cOfbz9H/en9yyExFbcRej9r+892d7wVMasNWKf7V6rbiROChp12/1/QFQenywtC3H7hXQT+67K8Frs4Yu+R53zasv5NDMxV+kP+DVduu0PmhXqQPcPvkHMfVYKv74hsvRv0Em7jpem5V2LQDZPhrUl/d0NNTwl8UcpLszw3AizXVn7jO2cjMvVGmftdEazXT+O8DBvEMiyr2hPFylmK9Uzshrves6t07kDviSq9h75o+qR3r2zcrRW06+B3gHt65an55Uvhu+B+fnFnTCsz2Put/lEdmgmcXulnoRz+QErAmGdGrvgesL8TdwdmVTv2uqDM6yIoKCNdRABlTvL+SYN/NqbpoNy3iz3YeMytWFQf17e9Ccqh4z96c3n5zwc/g3KfCQeXblvx1+XfQPmBvNrzEQurP2XXEFB0bFJS+ksT2Pw5hshfk54+69uJUB5grYvObNjylBnKgdZfDhz7YkfsNig/SD8x45XXMiu+gLKw5JvCGQ15lzqgHLXg0eH1rkgL2z9yyaKT03sVfLEWyv2qyP74C1Gr9kA5uouFoOy3piohXzki2ADlXl38zObvG8a2K6ZQzZdZx9mwOyehLOXtvlAO2ZLYEm+LroyA8sAPeX9cRaKr34GyoFU/jVreIT0N5aAT2nGNmnV/fRLKg84I1zobHb1OspdNZ+eP2H88duoi1oV+OrN4ztR3xu6EMr/diJ++EH+M3S/38rmMZk0un7UPO0dvdl3Q5C3wORrWZ2Fth+ZdDbtygecPwChYX2H3yK4P1mGsfWAdzNrA22arANY4WJ9g9wQre8H4kLey8wR79Tq840R531d7xwrpnrd0T1S6ZwvdkwPFuE/C6isHJuw/LX3viJ9yc9IfYpuefQXR/dR3UuGWzJiOs+Hxe7tnAqJ5w8PrJ6yrTySSdtPPvja999HHpxUcXPo4k7/OvJTXOd4QTdR/UTv76dU/JJ6fWyid/eWfQlcUERd2Lfr+5KE5LZU+R3+IOZZRebw2x3jSIH6lLKxMsm8I2vTLc2uWO0MCN8e3ouieqW0vhrWfWdtiUFcM+n7z++/kndO9mcjJrlprPVdNIbL1ksSq3M4h9ebJTxrRiClDSo4P+8c4l7766Qhke7/F0toRjicBUffqlszWhKC6cuzIwIsfD/6q4wXR8IdLxpjF/0z9Mh5/u6H1PVtJzV9Gn1/9yJdvT1qk+7BzUfScr3bI1+9LRotPKjtit/GTJsREbd5wekeNxshZiQpO7soI3DMPAO2ZiRvQzuanf/lx/8vzZ1OKDz5eV5lWm/L0lLExD7Yz1u9W1r5RK9jofyC7cNb0SZvxnRdGLY0/UkZdKLoU+OXWybsVfdftmC598tTu81vbAw+9tukT77mxruS6/6fv/XK/3C/3S/fyLzLnYAsAKAAA