apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ndau.fullname" . }}-ndaunode
  labels:
    app: {{ template "ndau.name" . }}
    chart: {{ template "ndau.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ndau.name" . }}-ndaunode
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ndau.name" . }}-ndaunode
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: noms-wait
        image: "{{ .Values.deployUtils.image.repository }}:{{ .Values.deployUtils.image.tag }}"
        imagePullPolicy: {{ .Values.deployUtils.image.pullPolicy }}
        command: ["sh", "-c", "echo starting noms wait loop; until curl -v {{ template "ndau.fullname" . }}-noms-service:{{ .Values.noms.port }}; do echo waiting for {{ template "ndau.fullname" . }}-noms-service; sleep 2; done;"]
      - name: config
        image: busybox
        command: ["/bin/sh", "/root/init.sh"]
        volumeMounts:
        - name: ndau-config-init
          mountPath: /root/init.sh
          subPath: init.sh
        - name: config-toml
          mountPath: /root/config-ro/config.toml
          subPath: config.toml
        - name: mock-chaos-msgp
          mountPath: /root/config-ro/mock-chaos.msgp
          subPath: mock-chaos.msgp
        - mountPath: "/root/.ndau"
          name: ndau-home-volume
      containers:
      - name: ndaunode
        image: "{{ .Values.ndaunode.image.repository }}:{{ .Values.ndaunode.image.tag }}"
        imagePullPolicy: {{ .Values.ndaunode.image.pullPolicy }}
        args: ["-spec", "http://{{ template "ndau.fullname" . }}-noms-service:{{ .Values.noms.port }}"]
        ports:
        - containerPort: 46658
        env:
        - name: NDAUHOME
          value: "/root/.ndau"
        volumeMounts:
        - mountPath: "/root/.ndau"
          name: ndau-home-volume
      volumes:
      - name: ndau-home-volume
        persistentVolumeClaim:
          claimName: {{ template "ndau.fullname" . }}-ndaunode-claim
      - name: config-toml
        configMap:
          name: {{ template "ndau.fullname" . }}-ndau-config
          items:
          - key: config.toml
            path: config.toml
      - name: ndau-config-init
        configMap:
          name: {{ template "ndau.fullname" . }}-ndau-config
          items:
          - key: init.sh
            path: init.sh
      - name: mock-chaos-msgp
        configMap:
          name: {{ template "ndau.fullname" . }}-ndau-config
          items:
          - key: mock-chaos.msgp
            path: mock-chaos.msgp

